### ISSUE TITLE
Where to put language files for the next-branch?

### ISSUE THREAD

**Issue by jankal** [COCOPi/cockpit-i18n#47]
Where shall up-to-date language files for the current next-release be stored?

I did a complete fresh transaltion of Cockpit into German for the current 0.8.7 version.

**Comment by aheinze** [comment]
Cockpit releases aren't shipped with language files. The idea is to collect all translations in this repo: https://github.com/agentejo/cockpit-i18n and download them if needed

**Comment by jankal** [comment]
Okay so I'll send a PR now.

**Comment by aheinze** [comment]
Thanks! 👍

**Comment by jankal** [comment]
See #48. This can be closed.
